# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_ADDRESS'] %>
  database: infinity_development


development:
  <<: *default
  database: infinity_development

test: &test
  <<: *default
  database: infinity_test

staging:
  <<: *default
  database: infinity_staging
  username: infinity
  password: <%= ENV['MYSQL_PASSWORD'] %>

production:
  <<: *default
  database: infinity_production
  username: infinity
  password: <%= ENV['MYSQL_PASSWORD'] %>

cucumber:
  <<: *test
